language: csharp
mono: none
dotnet: 2.1.502
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
  - osx
osx_image: xcode8.3
before_script:
  - dotnet restore ./Main/Accuweather.csproj
script:  
  - dotnet build ./Main/Accuweather.csproj -c Release